if(BUILD_TESTING)
  add_executable(daw_audio_hardware_tests tests/audio_hardware_tests.cpp)
  target_include_directories(daw_audio_hardware_tests PRIVATE engine)
  target_link_libraries(daw_audio_hardware_tests PRIVATE daw_core)
  target_compile_options(daw_audio_hardware_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME audio_hardware_transaction COMMAND daw_audio_hardware_tests)
  add_executable(daw_audio_device_tests tests/audio_device_tests.cpp)
  target_include_directories(daw_audio_device_tests PRIVATE engine)
  target_link_libraries(daw_audio_device_tests PRIVATE daw_core)
  target_compile_options(daw_audio_device_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME audio_device_selection COMMAND daw_audio_device_tests)
  add_executable(daw_mixer_group_tests tests/mixer_group_tests.cpp)
  target_include_directories(daw_mixer_group_tests PRIVATE engine tests)
  target_link_libraries(daw_mixer_group_tests PRIVATE daw_core)
  target_compile_options(daw_mixer_group_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME mixer_groups COMMAND daw_mixer_group_tests)
  add_executable(daw_mixer_gesture_tests tests/mixer_gesture_tests.cpp)
  target_include_directories(daw_mixer_gesture_tests PRIVATE engine tests)
  target_link_libraries(daw_mixer_gesture_tests PRIVATE daw_core)
  target_compile_options(daw_mixer_gesture_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME mixer_gestures COMMAND daw_mixer_gesture_tests)
  add_executable(daw_send_controls_tests tests/send_controls_tests.cpp)
  target_include_directories(daw_send_controls_tests PRIVATE engine tests)
  target_link_libraries(daw_send_controls_tests PRIVATE daw_core)
  target_compile_options(daw_send_controls_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
  add_test(NAME send_controls COMMAND daw_send_controls_tests)
  add_executable(daw_storage_jobs tests/storage_jobs.cpp)
  target_include_directories(daw_storage_jobs PRIVATE engine)
  target_link_libraries(daw_storage_jobs PRIVATE daw_core)
  add_test(NAME storage_jobs_crash COMMAND daw_storage_jobs)
  add_executable(daw_audio_tests tests/audio_tests.cpp)
  target_include_directories(daw_audio_tests PRIVATE engine)
  target_link_libraries(daw_audio_tests PRIVATE daw_core)
  add_test(NAME audio_render_storage COMMAND daw_audio_tests)
  add_executable(daw_import_jobs tests/import_jobs.cpp)
  target_include_directories(daw_import_jobs PRIVATE engine)
  target_link_libraries(daw_import_jobs PRIVATE daw_core)
  add_test(NAME background_wav_import COMMAND daw_import_jobs)
  add_executable(daw_aiff_import_tests tests/aiff_import_tests.cpp)
  target_include_directories(daw_aiff_import_tests PRIVATE engine)
  target_link_libraries(daw_aiff_import_tests PRIVATE daw_core)
  add_test(NAME aiff_import COMMAND daw_aiff_import_tests)
  if(NOT APPLE)
    add_executable(daw_resampler_tests tests/resampler_tests.cpp)
    target_include_directories(daw_resampler_tests PRIVATE engine)
    target_link_libraries(daw_resampler_tests PRIVATE daw_core)
    target_compile_options(daw_resampler_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
    add_test(NAME portable_resampler COMMAND daw_resampler_tests)
  endif()
  add_executable(daw_export_tests tests/export_tests.cpp)
  target_include_directories(daw_export_tests PRIVATE engine)
  target_link_libraries(daw_export_tests PRIVATE daw_core)
  add_test(NAME offline_wav_export COMMAND daw_export_tests)
  add_executable(daw_recording_recovery tests/recording_recovery.cpp)
  target_include_directories(daw_recording_recovery PRIVATE engine)
  target_link_libraries(daw_recording_recovery PRIVATE daw_core)
  add_test(NAME recording_crash_recovery COMMAND daw_recording_recovery)
  if(APPLE)
    set(DAW_VST3_TEST_PLUGIN "" CACHE PATH "Explicit path to the pinned SDK ADelay fixture")
    if(DAW_VST3_TEST_PLUGIN)
      if(NOT TARGET daw_vst3_scan_helper OR NOT TARGET daw_vst3_runtime_helper)
        message(FATAL_ERROR "DAW_VST3_TEST_PLUGIN requires both SDK-enabled VST3 helpers")
      endif()
      if(NOT IS_DIRECTORY "${DAW_VST3_TEST_PLUGIN}")
        message(FATAL_ERROR "VST3 test fixture does not exist: ${DAW_VST3_TEST_PLUGIN}")
      endif()
      find_package(Python3 REQUIRED COMPONENTS Interpreter)
      add_executable(daw_vst3_sdk_smoke tests/vst3_sdk_smoke.cpp)
      target_include_directories(daw_vst3_sdk_smoke PRIVATE engine)
      target_link_libraries(daw_vst3_sdk_smoke PRIVATE daw_core)
      target_compile_options(daw_vst3_sdk_smoke PRIVATE -Wall -Wextra -Wpedantic -Werror)
      add_dependencies(daw_vst3_sdk_smoke daw_vst3_scan_helper daw_vst3_runtime_helper)
      add_test(NAME vst3_sdk_smoke COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_SOURCE_DIR}/tests/run_vst3_sdk_smoke.py"
        "$<TARGET_FILE:daw_vst3_scan_helper>" "$<TARGET_FILE:daw_vst3_sdk_smoke>"
        "$<TARGET_FILE:daw_vst3_runtime_helper>" "${DAW_VST3_TEST_PLUGIN}")
      set_tests_properties(vst3_sdk_smoke PROPERTIES LABELS "vst3;sdk" TIMEOUT 60)
    endif()
    set(DAW_VST3_TEST_INSTRUMENT "" CACHE PATH "Explicit path to pinned SDK mda-vst3 with DX10")
    if(DAW_VST3_TEST_INSTRUMENT)
      if(NOT TARGET daw_vst3_scan_helper OR NOT TARGET daw_vst3_runtime_helper)
        message(FATAL_ERROR "DAW_VST3_TEST_INSTRUMENT requires both SDK-enabled VST3 helpers")
      endif()
      if(NOT IS_DIRECTORY "${DAW_VST3_TEST_INSTRUMENT}")
        message(FATAL_ERROR "VST3 instrument fixture does not exist: ${DAW_VST3_TEST_INSTRUMENT}")
      endif()
      find_package(Python3 REQUIRED COMPONENTS Interpreter)
      add_executable(daw_vst3_instrument_smoke tests/vst3_instrument_smoke.cpp)
      target_include_directories(daw_vst3_instrument_smoke PRIVATE engine)
      target_link_libraries(daw_vst3_instrument_smoke PRIVATE daw_core)
      target_compile_options(daw_vst3_instrument_smoke PRIVATE -Wall -Wextra -Wpedantic -Werror)
      add_dependencies(daw_vst3_instrument_smoke daw_vst3_scan_helper daw_vst3_runtime_helper)
      add_test(NAME vst3_instrument_source COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_SOURCE_DIR}/tests/run_vst3_sdk_smoke.py"
        "$<TARGET_FILE:daw_vst3_scan_helper>" "$<TARGET_FILE:daw_vst3_instrument_smoke>"
        "$<TARGET_FILE:daw_vst3_runtime_helper>" "${DAW_VST3_TEST_INSTRUMENT}" instrument)
      set_tests_properties(vst3_instrument_source PROPERTIES LABELS "vst3;sdk;instrument" TIMEOUT 100)
    endif()
    if(DAW_BUILD_VST3_RUNTIME_HELPER)
      add_executable(daw_vst3_runtime_isolation tests/vst3_runtime_isolation.cpp)
      target_include_directories(daw_vst3_runtime_isolation PRIVATE engine)
      target_link_libraries(daw_vst3_runtime_isolation PRIVATE daw_core)
      add_test(NAME vst3_runtime_isolation COMMAND daw_vst3_runtime_isolation)
    endif()
    add_executable(daw_au_host_probe tests/au_host_probe.cpp)
    target_include_directories(daw_au_host_probe PRIVATE engine)
    target_link_libraries(daw_au_host_probe PRIVATE daw_core)
    add_test(NAME approved_au_host COMMAND daw_au_host_probe)
    add_executable(daw_hardware_smoke tests/hardware_smoke.cpp)
    target_include_directories(daw_hardware_smoke PRIVATE engine)
    target_link_libraries(daw_hardware_smoke PRIVATE daw_core)
    add_executable(daw_duplex_hardware_smoke tests/duplex_hardware_smoke.cpp)
    target_include_directories(daw_duplex_hardware_smoke PRIVATE engine)
    target_link_libraries(daw_duplex_hardware_smoke PRIVATE daw_core)
    # MIDI capture tests are hardware-free by design: the packet parser, the
    # drop-oldest ring and host-time framing are pure logic, and open() without
    # a device must reject. Real controller capture stays a manual gate.
    add_executable(daw_midi_input_tests tests/midi_input_tests.cpp)
    target_include_directories(daw_midi_input_tests PRIVATE engine)
    target_link_libraries(daw_midi_input_tests PRIVATE daw_core)
    add_test(NAME midi_input COMMAND daw_midi_input_tests)
    # Device-dependent smoke/audition tests are intentionally NOT registered as
    # CTests: they require a real output/input device and are run manually on a
    # physical machine (see scripts/test-audio-preview.sh for the AU/VST3 browser
    # audition, and run daw_hardware_smoke / daw_duplex_hardware_smoke directly).
    # The shared CI runner is headless and has no audio device, so registering them
    # would break ctest on GitHub macOS runners.
    #
    # Note: daw_hardware_smoke and daw_duplex_hardware_smoke are built above but
    # deliberately kept out of CTest for the same reason (physical audio gate).
  endif()
  add_executable(daw_core_tests tests/core_tests.cpp)
  target_link_libraries(daw_core_tests PRIVATE daw_core)
  target_include_directories(daw_core_tests PRIVATE engine)
  add_test(NAME session_storage_bridge COMMAND daw_core_tests)
  add_executable(daw_c_header_test tests/c_header.c)
  target_link_libraries(daw_c_header_test PRIVATE daw_core)
  add_test(NAME pure_c_bridge COMMAND daw_c_header_test)
  add_executable(daw_dawproject_export_tests tests/dawproject_export_tests.cpp)
  target_include_directories(daw_dawproject_export_tests PRIVATE engine)
  target_link_libraries(daw_dawproject_export_tests PRIVATE daw_core)
  add_test(NAME dawproject_export COMMAND daw_dawproject_export_tests)
  add_executable(daw_project_package_tests tests/project_package_tests.cpp)
  target_include_directories(daw_project_package_tests PRIVATE engine)
  target_link_libraries(daw_project_package_tests PRIVATE daw_core)
  add_test(NAME project_package COMMAND daw_project_package_tests)
  add_executable(daw_midi_model_tests tests/midi_model_tests.cpp)
  target_include_directories(daw_midi_model_tests PRIVATE engine)
  target_link_libraries(daw_midi_model_tests PRIVATE daw_core)
  add_test(NAME midi_model COMMAND daw_midi_model_tests)
  add_executable(daw_midi_bridge_tests tests/midi_bridge_tests.cpp)
  target_include_directories(daw_midi_bridge_tests PRIVATE engine)
  target_link_libraries(daw_midi_bridge_tests PRIVATE daw_core)
  add_test(NAME midi_bridge COMMAND daw_midi_bridge_tests)
  add_executable(daw_tempo_model_tests tests/tempo_model_tests.cpp)
  target_include_directories(daw_tempo_model_tests PRIVATE engine)
  target_link_libraries(daw_tempo_model_tests PRIVATE daw_core)
  add_test(NAME tempo_model COMMAND daw_tempo_model_tests)
  add_executable(daw_marker_model_tests tests/markers_tests.cpp)
  target_include_directories(daw_marker_model_tests PRIVATE engine)
  target_link_libraries(daw_marker_model_tests PRIVATE daw_core)
  add_test(NAME marker_model COMMAND daw_marker_model_tests)
  add_executable(daw_clip_track_tests tests/clip_track_tests.cpp)
  target_include_directories(daw_clip_track_tests PRIVATE engine)
  target_link_libraries(daw_clip_track_tests PRIVATE daw_core)
  add_test(NAME clip_track_model COMMAND daw_clip_track_tests)
  # End-to-end scenario suite: one executable per user journey, each driving
  # the product through the same public C ABI as the macOS app and asserting
  # on durable artifacts. Files are discovered so adding a scenario is just
  # adding tests/e2e/e2e_<journey>.cpp; all carry the "e2e" CTest label
  # (run the group with: ctest --preset debug -L e2e).
  file(GLOB DAW_E2E_SOURCES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/tests/e2e/e2e_*.cpp")
  foreach(e2e_source ${DAW_E2E_SOURCES})
    get_filename_component(e2e_name ${e2e_source} NAME_WE)
    add_executable(${e2e_name} ${e2e_source})
    target_include_directories(${e2e_name} PRIVATE engine tests/e2e)
    target_link_libraries(${e2e_name} PRIVATE daw_core)
    target_compile_options(${e2e_name} PRIVATE -Wall -Wextra -Werror)
    if(APPLE AND TARGET daw_au_scan_helper)
      # The isolated AU scanner is a disposable helper process; the catalog
      # e2e scenario launches it by path, exactly as the macOS app resolves it.
      target_compile_definitions(${e2e_name} PRIVATE
        DAW_E2E_AU_SCAN_HELPER="$<TARGET_FILE:daw_au_scan_helper>")
    endif()
    add_test(NAME ${e2e_name} COMMAND ${e2e_name})
    set_tests_properties(${e2e_name} PROPERTIES LABELS "e2e" TIMEOUT 300)
  endforeach()
endif()
